### ISSUE TITLE
element inside a complextype element is refering to its own complextype element

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/R-EMD#19]
Is it normal that we can have this:
![image](https://user-images.githubusercontent.com/7910679/59916323-20668f00-941f-11e9-912a-d74a6388ae82.png)
where an 4_eml-coverage/8_Taxonomic Classification Type/4_taxonomic Classification element is refering to its own 4_eml-coverage/8_Taxonomic Classification Type complexType element?

**Comment by earnaud** [comment]
(Forgot to close the issue)
This is perfectly normal, allowing recursive treatment of metadata, thus producing ramified information.
